service: backend-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 # Cambia según tu preferencia
  memorySize: 128 # Ajusta si necesitas más
  timeout: 10 # Tiempo máximo de ejecución en segundos

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: '{proxy+}'
          method: any

package:
  exclude:
    - node_modules/aws-sdk/**  # AWS ya incluye esto, podemos excluirlo
    - package-lock.json

