/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "apisalud",
            "endpoint": "https://f9h95kv5wg.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:44181a4c-c27a-4c4f-ac5a-f35089241758",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_y2hEUVkZm",
    "aws_user_pools_web_client_id": "7o62mqhhpcpnj0kuqnhor1bena",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_YFJ1xmkf5",
        "userPoolWebClientId": "2l5k718rtppoup0s2j05c75lg"
    }
};


export default awsmobile;
